apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: frontend 
    port: 4000
    targetPort: {{ .Values.service.servicePort }}
    nodePort: 30043
  #- name: http 
 #   port: {{ .Values.service.servicePort }}
 #   targetPort: 3000
 #   nodePort: 32157
  selector:
    app: "{{  .Chart.Name }}"
