apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: frontend 
    protocol: TCP
    port: 32160
    targetPort: 8080
  - name: backend 
    protocol: TCP
    port: 32157
    targetPort: 3000
  selector:
    app: "{{  .Chart.Name }}"
